spring:
  datasource:
    url: jdbc:h2:file:./data/database
    username: test_db
    password: test_password
    driveClassName: org.h2.Driver
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
    console.settings.trace: false

